[[redirects]]
  from = "/backend"
  to = "https://eynosoftmvp.netlify.app/backend"
  status = 200
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"